### ISSUE TITLE
Show unlisted/private posts in Map

### ISSUE THREAD

**Issue by kandr3s** [jlelse/GoBlog#18]
At the moment only Published posts are shown in the Map.

Unlisted/Private posts should be visible in /map for logged-in users.

**Comment by kandr3s** [comment]
Maybe this should be changed to: Show Private/Unlisted posts in web indices (and inhenrently in the Map) for logged-in users?

**Comment by jlelse** [comment]
I created #26 for the indices, because the map isn't just a normal index.
