### ISSUE TITLE
Display post full content in feeds

### ISSUE THREAD

**Issue by kandr3s** [jlelse/GoBlog#24]
At the moment GoBlog only shows summaries of posts in feeds, even when the option "Show full content in summary" is activated.

**Comment by jlelse** [comment]
"Show full content in summary" is only used for the web indices. The full content is always included in the feeds, but it depends on the feed reader whether the full content or just the summary (that's included as well) get's displayed. RSS for example: Summary is in "description", full post content in "content:encoded". Which feed reader do you use?

**Comment by kandr3s** [comment]
I've tried yarr, Miniflux and Monocle with the same results.

**Comment by kandr3s** [comment]
In my case the full content is not being included in the feeds.

In the JSONFeed for example the fields content_html or content_text are not being generated, a summary field is generated and includes the first paragraph of the post, which is exactly the same as the <description> field in the Atom and RSS feeds that are generated. No other content field is included in the feeds.

Regardless of the reader only the summary is shown because it's the only content available in the feeds.

**Comment by jlelse** [comment]
Is that a public post? If yes, could you send me the link to see if I find the reason?

**Comment by kandr3s** [comment]
😬
