### ISSUE TITLE
Issue with the Project Name in Indonesia

### ISSUE THREAD

**Issue by stefanwuthrich** [jlelse/GoBlog#40]
Hi
I'm german speaking like you, and posted via https://twitter.com/golangch/status/1581260999658651650 about your nice project and learned, that the word "goblog" has a not-so-nice meaning (see the comments). 
Feel free to close the  "issue" :-)

**Comment by jlelse** [comment]
Hi, does it mean "stupid"?

**Comment by stefanwuthrich** [comment]
yes, stupid, ignorant :-)

**Comment by jlelse** [comment]
Ok, thanks. But it's called "GoBlog" with upper-case B, so I won't rename the project. 😄

**Comment by renofizaldy** [comment]
😂 i just knowing it on my google news feed and laughing so hard

**Comment by amrikasir** [comment]
AHAHAHAHAHA
I came here to laugh ✌️ ✌️
