### ISSUE TITLE
Add option for custom CSS

### ISSUE THREAD

**Issue by jlelse** [jlelse/GoBlog#54]
Add some easy way to modify the CSS.

**Comment by rjkreider** [comment]
I used a system in the past (ikiwiki cgi), and one way the custom CSS was able to be used was the system looked for a specific CSS file, such as "static/local.css", or whatever directory/file works for GoBlog -- it would then be included in the HTML head if it was found.  Not sure how this fits in the overall system for GoBlog capabilities, but just a quick thought/idea.

**Comment by jlelse** [comment]
Yes, that's an option. Another idea is to just add another entry to the settings. But what I'm not yet sure about is, whether the CSS should be replaced, merged or just added?

**Comment by skedastically** [comment]
Hi,

Would it be okay to add a toggle for replacing/merging/adding CSS? Currently, `embedded:customcss` only append the file I think.

Something like `mode: replace` in the yaml would be great. :)
