### ISSUE TITLE
Question/feature request: does GoBlog support outgoing proxy environment variables?

### ISSUE THREAD

**Issue by skedastically** [jlelse/GoBlog#69]
Hello,

I wanna ask if GoBlog supports sending outgoing requests with `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` like [GoToSocial](https://docs.gotosocial.org/en/latest/advanced/outgoing-proxy/) does. If not, would you consider this to be a feature request?

Furthermore, it would be great if `socks5h://` proxies are supported. I've [heard](https://github.com/containers/podman/issues/12883) that it's fairly new in Golang but it'd be nice to resolve DNS inside the SOCKS tunnel too.

Thank you

**Comment by jlelse** [comment]
HTTP_PROXY, HTTPS_PROXY and NO_PROXY should be already supported. I checked and only found it's missing for the check command, but all the other outgoing requests should respect the proxy env vars.

I will check how to use the x/net package for socks5h.

**Comment by jlelse** [comment]
I checked: With some small changes and Go 1.23, `socks5` and `socks5h` should be supported when you specify the `HTTP_PROXY` or `HTTPS_PROXY` environment variables.
